# Generated by Django 4.2 on 2023-12-17 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Price Config Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Price Configuration',
            },
        ),
        migrations.CreateModel(
            name='WaitingCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wait_time', models.FloatField(verbose_name='Wait time (in mins)')),
                ('wait_time_price', models.FloatField(verbose_name='price')),
                ('price_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='price.priceconfiguration')),
            ],
            options={
                'verbose_name_plural': 'Waiting Charges',
            },
        ),
        migrations.CreateModel(
            name='TimeMultiplierFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(verbose_name='time factor')),
                ('hours', models.FloatField(verbose_name='under hours')),
                ('price_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.priceconfiguration')),
            ],
            options={
                'verbose_name_plural': 'Time Multiplier Factor',
            },
        ),
        migrations.CreateModel(
            name='DistanceAdditionalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_kms', models.FloatField(verbose_name='threshold kms')),
                ('price_after_threshold', models.FloatField(verbose_name='price/km after threshold')),
                ('price_before_threshold', models.FloatField(verbose_name='price/km before threshold')),
                ('price_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='price.priceconfiguration')),
            ],
            options={
                'verbose_name_plural': 'Distance Additional Price',
            },
        ),
        migrations.CreateModel(
            name='DistanceBasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='base price')),
                ('kms', models.FloatField(verbose_name='kms upto')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], verbose_name='day')),
                ('price_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.priceconfiguration')),
            ],
            options={
                'verbose_name_plural': 'Distance Base Price',
                'unique_together': {('day', 'price_configuration')},
            },
        ),
    ]
